spring.application.name=repository-service
server.port=8082
management.endpoints.web.exposure.include=health,info,metrics,loggers,threaddump,env,beans
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true