"""Chunk and embedding persistence against the canonical schema, inside a rolled-back transaction."""

import os
from dataclasses import replace
from uuid import uuid4

import pytest

from backend.services.semantic.embeddings import OfflineEmbeddingProvider, EmbeddingDimensionError, vector_literal
from backend.services.semantic.profiles import DEFAULT_CHUNK_PROFILE, OFFLINE_EMBEDDING_PROFILE
from backend.services.semantic.store import (
    ProfileConflict, SourceMismatch, embed_analysis_chunks, index_analysis_chunks, register_chunk_profile,
    register_embedding_profile,
)

pytestmark = pytest.mark.skipif(not os.getenv("TEST_DATABASE_URL"), reason="TEST_DATABASE_URL is not set")

FILES = {
    "app/cart.py": b"import os\n\nclass Cart:\n    def add(self, item):\n        return item\n\n"
                   b"    def total(self):\n        return self.add(1)\n\ndef helper():\n    return os.getcwd()\n",
    "vendor/lib/util.py": b"def vendored():\n    return 1\n",
    "proto/order_pb2.py": b"# Generated by the protocol buffer compiler.  DO NOT EDIT!\ndef build():\n    return 1\n",
}


@pytest.fixture
def conn():
    from test_analysis_postgres import UncommittedConnection

    from backend.services.postgres import make_connection_factory

    real = make_connection_factory(os.environ["TEST_DATABASE_URL"])()
    try:
        yield UncommittedConnection(real)
    finally:
        real.rollback()
        real.close()


@pytest.fixture
def analysis(conn, tmp_path):
    from test_extraction_postgres import create_analysis, extract_into

    analysis_id = create_analysis(conn, sha=uuid4().hex[:8] * 5)
    extract_into(conn, tmp_path, analysis_id, FILES)
    return analysis_id


def read_source(path):
    return FILES[path]


def savepoint_raises(conn, error, statement, *args):
    import psycopg

    conn.execute("SAVEPOINT expect_error")
    with pytest.raises(getattr(psycopg, error)):
        conn.execute(statement, *args)
    conn.execute("ROLLBACK TO SAVEPOINT expect_error")


def count(conn, table, analysis_id):
    column = "c.analysis_id" if table == "embedding" else "analysis_id"
    join = " e JOIN semantic.chunk c ON c.id = e.chunk_id" if table == "embedding" else ""
    return conn.fetch_scalar(f"SELECT count(*) FROM semantic.{table}{join} WHERE {column} = %s", str(analysis_id))


# --- chunks --------------------------------------------------------------------------------------


def test_repeated_indexing_reuses_identical_chunks(conn, analysis):
    first = index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, read_source)
    second = index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, read_source)
    assert first.created == first.chunks > 0 and first.files == 1
    assert (second.created, second.reused) == (0, first.chunks)
    assert count(conn, "chunk", analysis) == first.chunks


def test_chunks_carry_their_analysis_version_file_entity_and_origin(conn, analysis):
    index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, read_source)
    rows = conn.fetch_all(
        "SELECT c.stable_chunk_key, c.repository_version_id = a.repository_version_id, e.stable_key, "
        "c.is_generated, c.is_vendored, c.start_byte IS NOT NULL FROM semantic.chunk c "
        "JOIN core.analysis a ON a.id = c.analysis_id LEFT JOIN core.entity e ON e.id = c.entity_id "
        "WHERE c.analysis_id = %s ORDER BY c.ordinal", str(analysis))
    keys = [row[0] for row in rows]
    assert keys[0] == "file:app/cart.py#0" and "method:app/cart.py::Cart.total#0" in keys
    assert all(row[1] and row[5] and row[3] is False and row[4] is False for row in rows)
    assert all(row[0].startswith(row[2] + "#") for row in rows)  # every chunk names its entity, FILE included


def test_generated_and_vendored_files_follow_the_profile_policy(conn, analysis):
    everything = replace(DEFAULT_CHUNK_PROFILE, profile_version=2, include_generated=True, include_vendored=True)
    result = index_analysis_chunks(conn, analysis, everything, read_source)
    assert result.files == 3
    origins = set(conn.fetch_all("SELECT DISTINCT is_generated, is_vendored FROM semantic.chunk "
                                 "WHERE analysis_id = %s", str(analysis)))
    assert origins == {(False, False), (True, False), (False, True)}


def test_chunks_are_only_built_from_the_analyzed_content(conn, analysis):
    with pytest.raises(SourceMismatch):
        index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, lambda path: FILES[path] + b"# edited\n")


def test_the_schema_enforces_version_origin_and_content_hash(conn, analysis):
    from test_extraction_postgres import create_analysis

    index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, read_source)
    chunk = conn.fetch_one("SELECT file_id, chunk_profile_id FROM semantic.chunk WHERE analysis_id = %s LIMIT 1",
                           str(analysis))
    other = create_analysis(conn, sha="e" * 40)
    other_version = conn.fetch_scalar("SELECT repository_version_id FROM core.analysis WHERE id = %s", str(other))
    insert = ("INSERT INTO semantic.chunk (analysis_id, repository_version_id, file_id, chunk_profile_id, "
              "stable_chunk_key, chunk_kind, content, content_hash, token_count, ordinal, start_line, end_line, "
              "is_generated, "
              "is_vendored) VALUES (%s, %s, %s, %s, 'k', 'CODE', 'x', %s, 1, 0, 1, 1, %s, false)")
    x_hash = "2d711642b726b04401627ca9fbac32f5c8530fb1903cc4db02258717921a4881"  # sha256("x")
    version = conn.fetch_scalar("SELECT repository_version_id FROM core.analysis WHERE id = %s", str(analysis))
    assert other_version != version
    savepoint_raises(conn, "IntegrityError", insert, str(analysis), str(other_version), str(chunk[0]),
                     str(chunk[1]), x_hash, False)  # the version must be the analysis's own
    savepoint_raises(conn, "IntegrityError", insert, str(analysis), str(version), str(chunk[0]), str(chunk[1]),
                     x_hash, True)  # origin flags must be the file's
    savepoint_raises(conn, "IntegrityError", insert, str(analysis), str(version), str(chunk[0]), str(chunk[1]),
                     "0" * 64, False)  # content hash must be the content's


def test_chunks_and_used_chunk_profiles_are_immutable(conn, analysis):
    index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, read_source)
    profile_id = register_chunk_profile(conn, DEFAULT_CHUNK_PROFILE)
    savepoint_raises(conn, "IntegrityError", "UPDATE semantic.chunk_profile SET code_version = 'changed' WHERE id = %s",
                     str(profile_id))
    savepoint_raises(conn, "IntegrityError", "UPDATE semantic.chunk SET ordinal = ordinal WHERE analysis_id = %s",
                     str(analysis))


def test_a_profile_version_cannot_be_reused_for_another_configuration(conn):
    register_chunk_profile(conn, DEFAULT_CHUNK_PROFILE)
    assert register_chunk_profile(conn, DEFAULT_CHUNK_PROFILE) == register_chunk_profile(conn, DEFAULT_CHUNK_PROFILE)
    with pytest.raises(ProfileConflict):
        register_chunk_profile(conn, replace(DEFAULT_CHUNK_PROFILE, max_tokens=64))


# --- embeddings ----------------------------------------------------------------------------------


def test_one_current_vector_per_chunk_profile_and_content(conn, analysis):
    chunks = index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, read_source).chunks
    provider = OfflineEmbeddingProvider()
    first = embed_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, OFFLINE_EMBEDDING_PROFILE, provider)
    second = embed_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, OFFLINE_EMBEDDING_PROFILE, provider)
    assert (first.embedded, second.embedded, second.already_current) == (chunks, 0, chunks)
    assert len(provider.calls) == 1  # nothing left to embed on the second run
    assert count(conn, "embedding", analysis) == chunks
    norms = conn.fetch_all("SELECT round(vector_norm(e.embedding)::numeric, 5) FROM semantic.embedding e "
                           "JOIN semantic.chunk c ON c.id = e.chunk_id WHERE c.analysis_id = %s", str(analysis))
    assert {row[0] for row in norms} == {1}  # the profile's L2 policy was applied


def test_a_new_embedding_profile_needs_neither_the_snapshot_nor_extraction(conn, analysis):
    chunks = index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, read_source).chunks
    embed_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, OFFLINE_EMBEDDING_PROFILE, OfflineEmbeddingProvider())
    entities_before = conn.fetch_scalar("SELECT count(*) FROM core.entity WHERE analysis_id = %s", str(analysis))
    v2 = replace(OFFLINE_EMBEDDING_PROFILE, profile_version=2, text_template="passage: {text}")
    result = embed_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, v2, OfflineEmbeddingProvider())
    assert result.embedded == chunks
    assert count(conn, "embedding", analysis) == 2 * chunks
    assert conn.fetch_scalar("SELECT count(*) FROM core.entity WHERE analysis_id = %s", str(analysis)) \
        == entities_before


def test_a_provider_returning_another_dimension_fails_and_writes_nothing(conn, analysis):
    index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, read_source)
    with pytest.raises(EmbeddingDimensionError, match="768-dimensional"):
        embed_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, OFFLINE_EMBEDDING_PROFILE,
                              OfflineEmbeddingProvider(dimension=768))
    assert count(conn, "embedding", analysis) == 0


def test_the_schema_rejects_other_dimensions_and_stale_content(conn, analysis):
    index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, read_source)
    chunk_id, content_hash = conn.fetch_one("SELECT id, content_hash FROM semantic.chunk WHERE analysis_id = %s "
                                            "LIMIT 1", str(analysis))
    profile_id = register_embedding_profile(conn, OFFLINE_EMBEDDING_PROFILE)
    insert = ("INSERT INTO semantic.embedding (chunk_id, embedding_profile_id, chunk_content_hash, embedding) "
              "VALUES (%s, %s, %s, %s::vector)")
    savepoint_raises(conn, "DataError", insert, str(chunk_id), str(profile_id), content_hash,
                     vector_literal([0.5] * 768))
    savepoint_raises(conn, "IntegrityError", insert, str(chunk_id), str(profile_id), "0" * 64,
                     vector_literal([0.5] * 3072))


def test_a_used_embedding_profile_only_changes_status(conn, analysis):
    index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, read_source)
    embed_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, OFFLINE_EMBEDDING_PROFILE, OfflineEmbeddingProvider())
    profile_id = register_embedding_profile(conn, OFFLINE_EMBEDDING_PROFILE)
    conn.execute("UPDATE semantic.embedding_profile SET status = 'RETIRED' WHERE id = %s", str(profile_id))
    savepoint_raises(conn, "IntegrityError",
                     "UPDATE semantic.embedding_profile SET model_revision = 'other' WHERE id = %s", str(profile_id))


# --- SS-DB-301 acceptance: references, duplicates, profile changes, deletion ---------------------


def test_an_embedding_needs_an_existing_chunk(conn, analysis):
    profile_id = register_embedding_profile(conn, OFFLINE_EMBEDDING_PROFILE)
    savepoint_raises(conn, "IntegrityError",
                     "INSERT INTO semantic.embedding (chunk_id, embedding_profile_id, chunk_content_hash, "
                     "is_first_party, embedding) VALUES (%s, %s, %s, true, %s::vector)",
                     str(uuid4()), str(profile_id), "0" * 64, vector_literal([0.5] * 3072))


def test_a_duplicate_embedding_is_rejected(conn, analysis):
    index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, read_source)
    embed_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, OFFLINE_EMBEDDING_PROFILE, OfflineEmbeddingProvider())
    chunk_id, profile_id, content_hash = conn.fetch_one(
        "SELECT e.chunk_id, e.embedding_profile_id, e.chunk_content_hash FROM semantic.embedding e "
        "JOIN semantic.chunk c ON c.id = e.chunk_id WHERE c.analysis_id = %s LIMIT 1", str(analysis))
    savepoint_raises(conn, "IntegrityError",
                     "INSERT INTO semantic.embedding (chunk_id, embedding_profile_id, chunk_content_hash, embedding) "
                     "VALUES (%s, %s, %s, %s::vector)", str(chunk_id), str(profile_id), content_hash,
                     vector_literal([0.5] * 3072))


def test_an_embedding_profile_cannot_change_its_dimension_or_revision(conn, analysis):
    profile_id = str(register_embedding_profile(conn, OFFLINE_EMBEDDING_PROFILE))
    savepoint_raises(conn, "IntegrityError", "UPDATE semantic.embedding_profile SET dimension = 768 WHERE id = %s",
                     profile_id)  # R1 has one physical dimension, used or not
    index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, read_source)
    embed_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, OFFLINE_EMBEDDING_PROFILE, OfflineEmbeddingProvider())
    for change in ("model_revision = 'gemini-embedding-002'", "model_name = 'other'", "distance_metric = 'L2'",
                   "normalization_policy = 'NONE'", "text_template = 'q: {text}'"):
        savepoint_raises(conn, "IntegrityError", f"UPDATE semantic.embedding_profile SET {change} WHERE id = %s",
                         profile_id)


def test_chunks_cannot_reference_another_analysis_file_or_entity(conn, analysis, tmp_path):
    from test_extraction_postgres import create_analysis, extract_into

    other = create_analysis(conn, sha="c" * 40)
    extract_into(conn, tmp_path / "other", other, {"app/cart.py": FILES["app/cart.py"]})
    index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, read_source)
    profile_id = str(register_chunk_profile(conn, DEFAULT_CHUNK_PROFILE))
    version = str(conn.fetch_scalar("SELECT repository_version_id FROM core.analysis WHERE id = %s", str(analysis)))
    own_file = str(conn.fetch_scalar("SELECT id FROM core.source_file WHERE analysis_id = %s AND path = 'app/cart.py'",
                                     str(analysis)))
    foreign_file = str(conn.fetch_scalar("SELECT id FROM core.source_file WHERE analysis_id = %s", str(other)))
    foreign_entity = str(conn.fetch_scalar("SELECT id FROM core.entity WHERE analysis_id = %s AND entity_type = 'CLASS'",
                                           str(other)))
    insert = ("INSERT INTO semantic.chunk (analysis_id, repository_version_id, file_id, entity_id, chunk_profile_id, "
              "stable_chunk_key, chunk_kind, content, content_hash, token_count, ordinal, start_line, end_line, "
              "is_generated, "
              "is_vendored) VALUES (%s, %s, %s, %s, %s, 'k', 'CODE', 'x', %s, 1, 0, 1, 1, false, false)")
    x_hash = "2d711642b726b04401627ca9fbac32f5c8530fb1903cc4db02258717921a4881"
    savepoint_raises(conn, "IntegrityError", insert, str(analysis), version, foreign_file, None, profile_id, x_hash)
    savepoint_raises(conn, "IntegrityError", insert, str(analysis), version, own_file, foreign_entity, profile_id,
                     x_hash)


def structural_counts(conn, analysis_id):
    return {table: conn.fetch_scalar(f"SELECT count(*) FROM core.{table} WHERE analysis_id = %s", str(analysis_id))
            for table in ("source_file", "entity", "evidence", "repository_edge")}


def test_deleting_derived_semantic_data_keeps_structural_facts(conn, analysis):
    index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, read_source)
    embed_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, OFFLINE_EMBEDDING_PROFILE, OfflineEmbeddingProvider())
    before = structural_counts(conn, analysis)
    conn.execute("DELETE FROM semantic.chunk WHERE analysis_id = %s", str(analysis))  # cascades to embeddings
    assert count(conn, "chunk", analysis) == 0 and count(conn, "embedding", analysis) == 0
    assert structural_counts(conn, analysis) == before and before["entity"] > 0


def test_deleting_an_analysis_cascades_to_its_chunks_and_vectors(conn, analysis):
    index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, read_source)
    embed_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, OFFLINE_EMBEDDING_PROFILE, OfflineEmbeddingProvider())
    chunk_ids = [str(row[0]) for row in conn.fetch_all("SELECT id FROM semantic.chunk WHERE analysis_id = %s",
                                                      str(analysis))]
    conn.execute("DELETE FROM core.analysis WHERE id = %s", str(analysis))
    assert conn.fetch_scalar("SELECT count(*) FROM semantic.chunk WHERE id = ANY(%s::uuid[])", chunk_ids) == 0
    assert conn.fetch_scalar("SELECT count(*) FROM semantic.embedding WHERE chunk_id = ANY(%s::uuid[])",
                             chunk_ids) == 0


def test_profiles_in_use_cannot_be_deleted(conn, analysis):
    index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, read_source)
    embed_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, OFFLINE_EMBEDDING_PROFILE, OfflineEmbeddingProvider())
    savepoint_raises(conn, "IntegrityError", "DELETE FROM semantic.chunk_profile WHERE id = %s",
                     str(register_chunk_profile(conn, DEFAULT_CHUNK_PROFILE)))
    savepoint_raises(conn, "IntegrityError", "DELETE FROM semantic.embedding_profile WHERE id = %s",
                     str(register_embedding_profile(conn, OFFLINE_EMBEDDING_PROFILE)))
