"""Generated and vendored files are flagged so first-party analysis can exclude them."""

import pytest

from backend.services.extraction.origin import classify_origin


@pytest.mark.parametrize("path, source, label", [
    ("app/service.py", b"def f(): pass\n", "first_party"),
    ("vendor/github.com/pkg/errors/errors.go", b"package errors\n", "vendored"),
    ("third_party/lib/util.py", b"x = 1\n", "vendored"),
    ("ios/Pods/Alamofire/Source.swift", b"", "vendored"),
    ("pandas/_libs/include/pandas/vendored/ujson/lib/ultrajson.h", b"", "vendored"),
    ("src/pip/_vendor/requests/api.py", b"", "vendored"),
    ("target/generated-sources/Api.java", b"class Api {}\n", "generated"),
    ("src/__generated__/schema.ts", b"", "generated"),
    ("proto/user_pb2.py", b"x = 1\n", "generated"),
    ("proto/user_pb2_grpc.py", b"x = 1\n", "generated"),
    ("api/user.pb.go", b"package api\n", "generated"),
    ("Forms/Main.designer.cs", b"", "generated"),
    ("app/migrations/0001_initial.py", b"# Generated by Django 5.0 on 2024-01-01\n", "generated"),
    ("gen/client.go", b"// Code generated by openapi-generator. DO NOT EDIT.\npackage gen\n", "generated"),
    ("lib/types.ts", b"/* @generated */\nexport type A = 1;\n", "generated"),
    # Conservative: ordinary names that merely mention generation stay first-party.
    ("app/generators/report.py", b"def generate(): pass\n", "first_party"),
    ("app/build/steps.py", b"x = 1\n", "first_party"),
    ("docs/code_generation.md", b"How code generated by us works\n", "first_party"),
])
def test_origin_classification(path, source, label):
    origin = classify_origin(path, source)
    assert origin.label == label, origin
    assert (origin.reason is None) == (label == "first_party")


def test_markers_are_only_read_from_the_file_header():
    source = b"x = 1\n" * 400 + b"# @generated\n"
    assert classify_origin("app/late.py", source).first_party
