"""SS-ML-301: source retention, the INDEXING stage, exclusions and restartable embedding.

Against the canonical schema inside one rolled-back transaction. The stage and the worker
commit and roll back their own connections; here they share the test transaction, and a
rollback is a no-op, so what a real commit would keep stays visible.
"""

import asyncio
import os
import shutil
import subprocess
from dataclasses import replace
from uuid import uuid4

import pytest

from backend.services.semantic.embeddings import (
    EmbeddingProfileIncompatible, EmbeddingProviderUnavailable, OfflineEmbeddingProvider,
)
from backend.services.semantic.profiles import (
    DEFAULT_CHUNK_PROFILE, DEFAULT_EMBEDDING_PROFILE, OFFLINE_EMBEDDING_PROFILE,
)
from backend.services.semantic.source_content import read_retained_source, retain_source_content
from backend.services.semantic.store import (
    SourceContentUnavailable, embed_analysis_chunks, index_analysis_chunks, register_chunk_profile,
)

pytestmark = pytest.mark.skipif(not os.getenv("TEST_DATABASE_URL"), reason="TEST_DATABASE_URL is not set")

AWS_KEY = b"AKIA" + b"QWERTYUIOPASDFGH"
FILES = {
    "app/cart.py": b"import os\n\nclass Cart:\n    def add(self, item):\n        return item\n\n"
                   b"    def total(self):\n        return self.add(1)\n\ndef helper():\n    return os.getcwd()\n",
    "app/settings.py": b"ACCESS_KEY = '" + AWS_KEY + b"'\n",
    "config/app.yaml": b"server:\n  port: 8080\n",
    "README.md": b"# Cart\nA cart service.\n\n## Usage\nCall add.\n",
    ".env": b"DATABASE_PASSWORD=hunter2\n",
    "assets/blob.py": b"x = 1\x00\n",
    "app/empty.py": b"\n\n",
    "vendor/lib/util.py": b"def vendored():\n    return 1\n",
    "proto/order_pb2.py": b"# Generated by the protocol buffer compiler.  DO NOT EDIT!\ndef build():\n    return 1\n",
}


class SharedConnection:
    """One transaction for everything: commit, rollback and close are no-ops."""

    def __init__(self, conn):
        self._conn = conn

    def __getattr__(self, name):
        return getattr(self._conn, name)

    def commit(self):
        pass

    def rollback(self):
        pass

    def close(self):
        pass


@pytest.fixture
def conn():
    from backend.services.postgres import make_connection_factory

    real = make_connection_factory(os.environ["TEST_DATABASE_URL"])()
    try:
        yield SharedConnection(real)
    finally:
        real.rollback()
        real.close()


def extracted(conn, tmp_path, files, *, retain=True):
    from test_extraction_postgres import create_analysis, extract_into

    analysis_id = create_analysis(conn, sha=uuid4().hex[:8] * 5)
    extract_into(conn, tmp_path, analysis_id, files)
    if retain:
        retain_source_content(conn, analysis_id, files.__getitem__)
    return analysis_id


@pytest.fixture
def analysis(conn, tmp_path):
    return extracted(conn, tmp_path, FILES)


def scalar(conn, query, *args):
    return conn.fetch_scalar(query, *(str(a) for a in args))


def embeddings_of(conn, analysis_id):
    return scalar(conn, "SELECT count(*) FROM semantic.embedding e JOIN semantic.chunk c ON c.id = e.chunk_id "
                        "WHERE c.analysis_id = %s", analysis_id)


# --- retention -----------------------------------------------------------------------------------


def test_source_is_retained_by_policy_and_secrets_are_never_stored(conn, analysis):
    statuses = dict(conn.fetch_all("SELECT path, content_status FROM core.source_file WHERE analysis_id = %s",
                                   str(analysis)))
    assert statuses == {
        "app/cart.py": "RETAINED", "app/settings.py": "SECRET", "config/app.yaml": "RETAINED",
        "README.md": "RETAINED", ".env": "SECRET", "assets/blob.py": "BINARY", "app/empty.py": "RETAINED",
        "vendor/lib/util.py": "RETAINED", "proto/order_pb2.py": "RETAINED",
    }
    retained = read_retained_source(conn, analysis)
    assert sorted(retained.values()) == sorted(FILES[path] for path, status in statuses.items()
                                               if status == "RETAINED")
    for secret in (AWS_KEY, b"hunter2"):
        assert scalar(conn, "SELECT count(*) FROM core.source_content WHERE position(%s::bytea IN content) > 0",
                      secret.decode()) == 0


def test_identical_content_is_stored_once_across_analyses(conn, analysis, tmp_path):
    again = extracted(conn, tmp_path / "again", {"app/cart.py": FILES["app/cart.py"]})
    hashes = conn.fetch_all("SELECT retained_content_hash FROM core.source_file WHERE path = 'app/cart.py' "
                            "AND analysis_id = ANY(%s::uuid[])", [str(analysis), str(again)])
    assert len({row[0] for row in hashes}) == 1
    assert scalar(conn, "SELECT count(*) FROM core.source_content WHERE content_hash = %s", hashes[0][0]) == 1


def test_retention_refuses_a_snapshot_that_differs_from_the_extraction(conn, tmp_path):
    from backend.services.semantic.source_content import SourceContentMismatch

    analysis_id = extracted(conn, tmp_path, {"a.py": b"x = 1\n"}, retain=False)
    with pytest.raises(SourceContentMismatch):
        retain_source_content(conn, analysis_id, lambda path: b"x = 2\n")


# --- chunks --------------------------------------------------------------------------------------


def test_chunks_come_from_retained_source_and_map_to_entities_and_exact_evidence(conn, analysis):
    result = index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE)
    assert result.created == result.chunks > 0
    rows = conn.fetch_all(
        "SELECT c.chunk_kind, f.path, e.stable_key, e.entity_type, c.start_line, c.end_line, c.start_byte, "
        "c.end_byte, c.content, c.metadata->>'section', e.start_line, e.end_line "
        "FROM semantic.chunk c JOIN core.source_file f ON f.id = c.file_id JOIN core.entity e ON e.id = c.entity_id "
        "WHERE c.analysis_id = %s ORDER BY f.path, c.ordinal", str(analysis))
    assert len(rows) == result.chunks  # every chunk names a canonical entity
    kinds = {(path, kind) for kind, path, *_ in rows}
    assert kinds == {("app/cart.py", "CODE"), ("app/cart.py", "CLASS"), ("app/cart.py", "METHOD"),
                     ("app/cart.py", "FUNCTION"), ("config/app.yaml", "CONFIGURATION"),
                     ("README.md", "DOCUMENTATION")}
    retained = {path: FILES[path] for path in FILES}
    for kind, path, key, entity_type, start, end, start_byte, end_byte, content, section, e_start, e_end in rows:
        assert retained[path][start_byte:end_byte].decode() == content  # exact bytes of the analyzed file
        assert e_start <= start <= end <= e_end  # inside its entity's evidence
        if kind in ("CODE", "CONFIGURATION", "DOCUMENTATION"):
            assert (entity_type, key) == ("FILE", f"file:{path}")
        else:
            assert entity_type == kind
    assert [row[9] for row in rows if row[1] == "README.md"] == ["# Cart", "## Usage"]


def test_every_file_without_chunks_has_a_recorded_reason(conn, analysis):
    result = index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE)
    reasons = dict(conn.fetch_all(
        "SELECT f.path, x.reason FROM semantic.chunk_exclusion x JOIN core.source_file f ON f.id = x.file_id "
        "WHERE x.analysis_id = %s", str(analysis)))
    assert reasons == {"app/settings.py": "SECRET", ".env": "SECRET", "assets/blob.py": "BINARY",
                       "app/empty.py": "NO_INDEXABLE_CONTENT", "vendor/lib/util.py": "VENDORED",
                       "proto/order_pb2.py": "GENERATED"}
    assert result.exclusions == {"BINARY": 1, "GENERATED": 1, "NO_INDEXABLE_CONTENT": 1, "SECRET": 2, "VENDORED": 1}
    assert result.files + result.skipped_files == len(FILES)
    assert conn.fetch_scalar("SELECT count(*) FROM semantic.chunk c JOIN core.source_file f ON f.id = c.file_id "
                             "WHERE c.analysis_id = %s AND f.path = ANY(%s::text[])", str(analysis),
                             list(reasons)) == 0


def test_oversized_and_excluded_kinds_are_recorded_too(conn, tmp_path):
    from backend.services.semantic import source_content

    files = {"app/a.py": b"def a():\n    return 1\n", "docs/guide.md": b"# Guide\ntext\n",
             "data/big.py": b"x = 1\n" * 40}
    original = source_content.MAX_RETAINED_BYTES
    source_content.MAX_RETAINED_BYTES = 100
    try:
        analysis_id = extracted(conn, tmp_path, files)
    finally:
        source_content.MAX_RETAINED_BYTES = original
    code_only = replace(DEFAULT_CHUNK_PROFILE, profile_version=90,
                        included_entity_types=("CLASS", "INTERFACE", "FUNCTION", "METHOD", "FILE"))
    assert index_analysis_chunks(conn, analysis_id, code_only).exclusions == {
        "KIND_NOT_INCLUDED": 1, "OVERSIZED": 1}


def test_an_analysis_extracted_before_retention_fails_clearly(conn, tmp_path):
    analysis_id = extracted(conn, tmp_path, {"a.py": b"x = 1\n"}, retain=False)
    with pytest.raises(SourceContentUnavailable, match="analyze it again") as caught:
        index_analysis_chunks(conn, analysis_id, DEFAULT_CHUNK_PROFILE)
    assert caught.value.failure_code == "SOURCE_CONTENT_UNAVAILABLE"


def test_chunk_identities_are_stable_across_identical_analyses(conn, analysis, tmp_path):
    again = extracted(conn, tmp_path / "again", FILES)
    for analysis_id in (analysis, again):
        index_analysis_chunks(conn, analysis_id, DEFAULT_CHUNK_PROFILE)
    identities = [conn.fetch_all("SELECT stable_chunk_key, content_hash, chunk_kind, start_byte, end_byte "
                                 "FROM semantic.chunk WHERE analysis_id = %s ORDER BY stable_chunk_key", str(a))
                  for a in (analysis, again)]
    assert identities[0] == identities[1] and identities[0]


# --- embeddings ----------------------------------------------------------------------------------


class FailingAfter(OfflineEmbeddingProvider):
    """Embeds ``batches`` batches, then fails as an unavailable provider would."""

    def __init__(self, batches):
        super().__init__()
        self.remaining = batches

    def embed(self, texts, *, profile, task):
        if self.remaining == 0:
            raise EmbeddingProviderUnavailable("provider unavailable (503 UNAVAILABLE)")
        self.remaining -= 1
        return super().embed(texts, profile=profile, task=task)


def test_a_provider_failure_resumes_without_duplicate_vectors(conn, analysis):
    chunks = index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE).chunks
    assert chunks > 4
    with pytest.raises(EmbeddingProviderUnavailable):
        embed_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, OFFLINE_EMBEDDING_PROFILE, FailingAfter(2),
                              batch_size=2, commit_each_batch=True)
    assert embeddings_of(conn, analysis) == 4  # two committed batches survive the failure

    healthy = OfflineEmbeddingProvider()
    resumed = embed_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, OFFLINE_EMBEDDING_PROFILE, healthy,
                                    batch_size=2, commit_each_batch=True)
    assert (resumed.already_current, resumed.embedded) == (4, chunks - 4)
    assert sum(len(call) for call in healthy.calls) == chunks - 4  # nothing is embedded twice
    assert embeddings_of(conn, analysis) == chunks
    assert scalar(conn, "SELECT count(*) FROM (SELECT chunk_id FROM semantic.embedding e JOIN semantic.chunk c "
                        "ON c.id = e.chunk_id WHERE c.analysis_id = %s GROUP BY chunk_id, embedding_profile_id "
                        "HAVING count(*) > 1) d", analysis) == 0


def test_an_incompatible_provider_is_refused_before_anything_is_written(conn, analysis):
    index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE)
    provider = OfflineEmbeddingProvider()
    with pytest.raises(EmbeddingProfileIncompatible):
        embed_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, DEFAULT_EMBEDDING_PROFILE, provider)
    assert provider.calls == [] and embeddings_of(conn, analysis) == 0
    assert scalar(conn, "SELECT count(*) FROM semantic.embedding_profile WHERE configuration_fingerprint = %s",
                  DEFAULT_EMBEDDING_PROFILE.fingerprint) == 0


def test_documents_are_embedded_with_their_identifiers(conn, analysis):
    index_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE)
    provider = OfflineEmbeddingProvider()
    embed_analysis_chunks(conn, analysis, DEFAULT_CHUNK_PROFILE, OFFLINE_EMBEDDING_PROFILE, provider)
    texts = [text for call in provider.calls for text in call]
    add = next(t for t in texts if t.endswith("    def add(self, item):\n        return item"))
    assert add.startswith("path: app/cart.py\nkind: METHOD\nsymbol: ") and "Cart.add" in add.split("\n")[2]
    assert any(t.startswith("path: README.md\nkind: DOCUMENTATION\nsymbol: ## Usage\n\n## Usage") for t in texts)


# --- the INDEXING stage --------------------------------------------------------------------------


def run_stage(conn, analysis_id, provider, **options):
    from types import SimpleNamespace

    from backend.services.semantic.stage import SemanticIndexingStage

    stage = SemanticIndexingStage(lambda: conn, provider, embedding_profile=OFFLINE_EMBEDDING_PROFILE, **options)
    attempt_id = uuid4()  # the stage reads only the identifiers of the extraction result
    return asyncio.run(stage(SimpleNamespace(analysis_id=analysis_id, attempt_id=attempt_id))), attempt_id


def test_reprocessing_identical_content_reuses_chunks_and_vectors(conn, analysis):
    first_provider, second_provider = OfflineEmbeddingProvider(), OfflineEmbeddingProvider()
    assert run_stage(conn, analysis, first_provider)[0] == "AWAITING_STAGE"
    outcome, attempt_id = run_stage(conn, analysis, second_provider)
    assert outcome == "AWAITING_STAGE" and second_provider.calls == []
    metrics = conn.fetch_scalar("SELECT metadata->'indexing'->%s FROM core.analysis WHERE id = %s",
                                str(attempt_id), str(analysis))
    assert metrics["chunks_created"] == 0 and metrics["chunks_reused"] == metrics["chunks"] > 0
    assert metrics["vectors_created"] == 0 and metrics["vectors_reused"] == metrics["chunks"]
    assert metrics["exclusions"]["SECRET"] == 2


def test_the_stage_refuses_an_incompatible_provider_at_construction(conn):
    from backend.services.semantic.stage import SemanticIndexingStage

    with pytest.raises(EmbeddingProfileIncompatible):
        SemanticIndexingStage(lambda: conn, OfflineEmbeddingProvider(), embedding_profile=DEFAULT_EMBEDDING_PROFILE)


def _repository(tmp_path):
    from test_analysis_postgres import _local_repository

    source, _ = _local_repository(tmp_path)
    for path in ("svc.py", "config/app.yaml", "README.md", "app/settings.py"):
        content = {"svc.py": FILES["app/cart.py"], "config/app.yaml": FILES["config/app.yaml"],
                   "README.md": FILES["README.md"], "app/settings.py": FILES["app/settings.py"]}[path]
        (source / path).parent.mkdir(parents=True, exist_ok=True)
        (source / path).write_bytes(content)
    identity = ["-c", "user.name=t", "-c", "user.email=t@example.com"]
    subprocess.run(["git", *identity, "add", "-A"], cwd=source, check=True, capture_output=True)
    subprocess.run(["git", *identity, "commit", "-qm", "two"], cwd=source, check=True, capture_output=True)
    sha = subprocess.run(["git", "rev-parse", "HEAD"], cwd=source, check=True, capture_output=True,
                         text=True).stdout.strip()
    return source, sha


def _queued(conn, sha):
    from backend.services.analysis_persistence import create_or_reuse_analysis

    name = f"repo-{uuid4().hex[:8]}"
    return create_or_reuse_analysis(
        conn, canonical_repository_key=f"github:test-owner/{name}", owner_name="test-owner", repository_name=name,
        clone_url=f"https://github.com/test-owner/{name}.git", requested_reference="main",
        resolved_commit_sha=sha, structural_pipeline_version="structural-test")


def _pipeline(conn, acquirer, indexing=None):
    from backend.services.analysis_pipeline import AnalysisPipeline
    from backend.services.extraction.stage import StructuralExtractionStage

    return AnalysisPipeline(lambda: conn, acquirer, ownership_check_seconds=60,
                            structural_stage=StructuralExtractionStage(lambda: conn, next_stage=indexing))


def _acquirer(tmp_path, source, acquisitions):
    from backend.services.repository_acquisition import GitRepositoryAcquirer

    class CountingAcquirer(GitRepositoryAcquirer):
        def acquire(self, request, **kwargs):
            acquisitions.append(request.attempt_id)
            return super().acquire(request, **kwargs)

    return CountingAcquirer(workdir_root=tmp_path / "work", remote_url_for=lambda key: source.as_uri(),
                            allowed_protocols=("file",))


def _resume(conn, pipeline, expected):
    from backend.services.analysis_worker import _failure_of, claim_analysis_transactionally, complete_attempt

    claimed = claim_analysis_transactionally(lambda: conn, pipeline.resumable_stages)
    if claimed is None or claimed[0] != expected:
        pytest.skip("another parked analysis is ahead of the test row")
    analysis_id, attempt_id = claimed
    try:
        outcome = asyncio.run(pipeline(analysis_id, attempt_id))
        asyncio.run(complete_attempt(lambda: conn, analysis_id=analysis_id, attempt_id=attempt_id, outcome=outcome))
    except Exception as exc:
        code, detail = _failure_of(exc)
        asyncio.run(complete_attempt(lambda: conn, analysis_id=analysis_id, attempt_id=attempt_id, outcome="FAILED",
                                     failure_code=code, failure_detail=detail))
    return analysis_id, attempt_id


def _state(conn, analysis_id):
    from backend.routers.analyses import _get_analysis

    state = _get_analysis(conn, analysis_id)
    return state.status, state.last_completed_stage, state.awaiting_stage


def _semantic_counts(conn, analysis_id):
    return (scalar(conn, "SELECT count(*) FROM semantic.chunk WHERE analysis_id = %s", analysis_id),
            embeddings_of(conn, analysis_id))


@pytest.mark.skipif(shutil.which("git") is None, reason="git is not installed")
def test_a_fresh_analysis_is_indexed_and_parks_awaiting_projecting(conn, tmp_path):
    from test_analysis_postgres import _process_claimed

    from backend.services.semantic.stage import SemanticIndexingStage

    source, sha = _repository(tmp_path)
    created = _queued(conn, sha)
    acquisitions = []
    stage = SemanticIndexingStage(lambda: conn, OfflineEmbeddingProvider(), embedding_profile=OFFLINE_EMBEDDING_PROFILE)
    attempt = asyncio.run(_process_claimed(conn, _pipeline(conn, _acquirer(tmp_path, source, acquisitions), stage),
                                           created))

    assert _state(conn, created.analysis_id) == ("AWAITING_STAGE", "INDEXING", "PROJECTING")
    chunks, vectors = _semantic_counts(conn, created.analysis_id)
    assert chunks == vectors > 0
    metrics = scalar(conn, "SELECT metadata->'indexing'->%s FROM core.analysis WHERE id = %s", attempt,
                     created.analysis_id)
    assert metrics["exclusions"] == {"SECRET": 1} and metrics["embedding_profile"] == "offline-sha256-3072/1"


@pytest.mark.skipif(shutil.which("git") is None, reason="git is not installed")
def test_a_parked_analysis_is_indexed_without_acquisition_or_extraction(conn, tmp_path):
    from test_analysis_postgres import _process_claimed
    from test_extraction_postgres import counts

    from backend.services.semantic.stage import SemanticIndexingStage

    source, sha = _repository(tmp_path)
    created = _queued(conn, sha)
    acquisitions = []
    acquirer = _acquirer(tmp_path, source, acquisitions)
    first = asyncio.run(_process_claimed(conn, _pipeline(conn, acquirer), created))  # no indexing deployed
    assert _state(conn, created.analysis_id) == ("AWAITING_STAGE", "EXTRACTING", "INDEXING")
    structural = counts(conn, created.analysis_id)

    # Indexing is deployed, but the provider fails: the resumed attempt fails, nothing is re-acquired.
    flaky = SemanticIndexingStage(lambda: conn, FailingAfter(1), embedding_profile=OFFLINE_EMBEDDING_PROFILE,
                                  batch_size=2)
    analysis_id, second = _resume(conn, _pipeline(conn, acquirer, flaky), created.analysis_id)
    assert analysis_id == created.analysis_id and second != first
    assert _state(conn, analysis_id) == ("FAILED", "EXTRACTING", "INDEXING")
    assert scalar(conn, "SELECT failure_code FROM core.analysis_attempt WHERE id = %s", second) \
        == "EMBEDDING_PROVIDER_UNAVAILABLE"
    chunks, partial = _semantic_counts(conn, analysis_id)
    assert partial == 2 and chunks > partial

    # A retry resumes at INDEXING, embeds only what is missing, and parks awaiting PROJECTING.
    from backend.services.analysis_lifecycle import requeue_failed_analysis

    asyncio.run(requeue_failed_analysis(conn, analysis_id, requested_by="pytest"))
    assert _state(conn, analysis_id) == ("AWAITING_STAGE", "EXTRACTING", "INDEXING")
    healthy = OfflineEmbeddingProvider()
    healthy_stage = SemanticIndexingStage(lambda: conn, healthy, embedding_profile=OFFLINE_EMBEDDING_PROFILE)
    _, third = _resume(conn, _pipeline(conn, acquirer, healthy_stage), created.analysis_id)

    assert _state(conn, analysis_id) == ("AWAITING_STAGE", "INDEXING", "PROJECTING")
    assert acquisitions == [first]  # acquired once, by the extracting attempt
    assert counts(conn, analysis_id) == structural  # extracted once
    assert _semantic_counts(conn, analysis_id) == (chunks, chunks)
    assert sum(len(call) for call in healthy.calls) == chunks - partial
    assert list((tmp_path / "work").iterdir()) == []


@pytest.mark.skipif(shutil.which("git") is None, reason="git is not installed")
def test_a_fresh_analysis_whose_indexing_fails_retries_at_indexing(conn, tmp_path):
    from test_analysis_postgres import _process_claimed

    from backend.services.analysis_lifecycle import requeue_failed_analysis
    from backend.services.semantic.stage import SemanticIndexingStage

    source, sha = _repository(tmp_path)
    created = _queued(conn, sha)
    acquisitions = []
    acquirer = _acquirer(tmp_path, source, acquisitions)
    broken = SemanticIndexingStage(lambda: conn, FailingAfter(0), embedding_profile=OFFLINE_EMBEDDING_PROFILE)
    asyncio.run(_process_claimed(conn, _pipeline(conn, acquirer, broken), created))
    assert _state(conn, created.analysis_id) == ("FAILED", "EXTRACTING", "INDEXING")

    asyncio.run(requeue_failed_analysis(conn, created.analysis_id, requested_by="pytest"))
    healthy = SemanticIndexingStage(lambda: conn, OfflineEmbeddingProvider(),
                                    embedding_profile=OFFLINE_EMBEDDING_PROFILE)
    _resume(conn, _pipeline(conn, acquirer, healthy), created.analysis_id)
    assert _state(conn, created.analysis_id) == ("AWAITING_STAGE", "INDEXING", "PROJECTING")
    assert len(acquisitions) == 1
