"""Classify files as first-party, generated or vendored.

Flagged files are still extracted (their evidence stays available) but are marked in
``core.source_file.is_generated`` / ``is_vendored`` so architecture classification,
entity counts and crash thresholds can consider first-party code only. The rules
are deliberately conservative: a false "generated" flag hides real code, so only
unambiguous directory names, file-name conventions and explicit header markers count.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

VENDORED_DIRS = frozenset({
    "vendor", "vendors", "vendored", "_vendor", "third_party", "third-party", "thirdparty", "3rdparty", "3rd_party",
    "pods", "carthage", "jspm_packages", "site-packages", "dist-packages", "godeps",
})
GENERATED_DIRS = frozenset({
    "generated", "__generated__", "_generated", "generated-sources", "generated-test-sources",
    "generated_sources", "gen-src",
    "src_managed",  # sbt: sources produced by source generators (ScalaPB, BuildInfo, Twirl)
})
GENERATED_NAMES = re.compile(
    r"(_pb2(_grpc)?\.pyi?|\.pb\.go|_pb\.js|_pb\.d\.ts|_grpc\.pb\.go|\.generated\.[a-z0-9]+|\.g\.(cs|dart)"
    r"|\.designer\.cs|\.freezed\.dart|_generated\.go)$",
    re.IGNORECASE,
)
GENERATED_MARKERS = re.compile(
    rb"@generated|code generated .{0,80}do not edit|generated by (django|the protocol buffer compiler|protoc|"
    rb"openapi|swagger|jooq|antlr|thrift|mybatis|hibernate|grpc|the scala plugin for the protocol buffer compiler)|this file (is|was) (automatically|auto-?) ?generated"
    rb"|auto-?generated (file|code)|<auto-generated",
    re.IGNORECASE,
)
_HEADER_BYTES = 1024


@dataclass(frozen=True)
class Origin:
    is_generated: bool = False
    is_vendored: bool = False
    reason: str | None = None

    @property
    def first_party(self) -> bool:
        return not (self.is_generated or self.is_vendored)

    @property
    def label(self) -> str:
        return "vendored" if self.is_vendored else "generated" if self.is_generated else "first_party"


def classify_origin(path: str, source: bytes) -> Origin:
    parts = [part.lower() for part in path.split("/")]
    directories, name = parts[:-1], parts[-1]
    vendored = next((d for d in directories if d in VENDORED_DIRS), None)
    if vendored:
        return Origin(is_vendored=True, reason=f"directory:{vendored}")
    generated = next((d for d in directories if d in GENERATED_DIRS), None)
    if generated:
        return Origin(is_generated=True, reason=f"directory:{generated}")
    if GENERATED_NAMES.search(name):
        return Origin(is_generated=True, reason="file_name")
    if GENERATED_MARKERS.search(source[:_HEADER_BYTES]):
        return Origin(is_generated=True, reason="header_marker")
    return Origin()
