# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto
from google.protobuf import descriptor_pool


class OrderMessage:
    def SerializeToString(self):
        return descriptor_pool.Default().FindMessageTypeByName("Order").name
